s = set()
user_nunmber_1 = int(input("Enter number 1: "))
s.add(user_nunmber_1)
user_nunmber_2 = int(input("Enter number 2: "))
s.add(user_nunmber_2)
user_nunmber_3 = int(input("Enter number 3: "))
s.add(user_nunmber_3)
user_nunmber_4 = int(input("Enter number 4: "))
s.add(user_nunmber_4)
user_nunmber_5 = int(input("Enter number 5: "))
s.add(user_nunmber_5)
user_nunmber_6 = int(input("Enter number 6: "))
s.add(user_nunmber_6)
user_nunmber_7 = int(input("Enter number 7: "))
s.add(user_nunmber_7)
user_nunmber_8 = int(input("Enter number 8: "))
s.add(user_nunmber_8)

print(s)