fruits_list = []
user_enter_name_1 = input("Enter fruit name 1: ")
user_enter_name_2 = input("Enter fruit name 2: ")
user_enter_name_3 = input("Enter fruit name 3: ")
user_enter_name_4 = input("Enter fruit name 4: ")
user_enter_name_5 = input("Enter fruit name 5: ")
user_enter_name_6 = input("Enter fruit name 6: ")
user_enter_name_7 = input("Enter fruit name 7: ")
fruits_list.append(user_enter_name_1)
fruits_list.append(user_enter_name_2)
fruits_list.append(user_enter_name_3)
fruits_list.append(user_enter_name_4)
fruits_list.append(user_enter_name_5)
fruits_list.append(user_enter_name_6)
fruits_list.append(user_enter_name_7)
print(fruits_list)