list = []
stu_1 = int(input("Enter student 1 marks: "))
stu_2 = int(input("Enter student 2 marks: "))
stu_3 = int(input("Enter student 3 marks: "))
stu_4 = int(input("Enter student 4 marks: "))
stu_5 = int(input("Enter student 5 marks: "))
stu_6 = int(input("Enter student 6 marks: "))
list.append(stu_1)
list.append(stu_2)
list.append(stu_3)
list.append(stu_4)
list.append(stu_5)
list.append(stu_6)
list.sort()
print(list)